"""empty message

Revision ID: c5496fa1776c
Revises: 7fd53ca52e00
Create Date: 2024-05-21 11:33:29.894530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5496fa1776c'
down_revision = '7fd53ca52e00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(), nullable=False))
        batch_op.drop_column('texto')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comentario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texto', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('text')

    # ### end Alembic commands ###
